# Generated by Django 4.1.4 on 2023-01-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(blank=True, choices=[('AI', 'Arteficial Intelligence'), ('WEB', 'Web Developing'), ('ELEC', 'Electrical Engineering'), ('MECH', 'Mechanical Engineering')], default='A', help_text='Enter a Post genre (A(AI), W(WEB), E(Electrical), M(Mechanical))', max_length=10),
        ),
    ]
