# Generated by Django 4.1.4 on 2022-12-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_jobs', to='job.job')),
                ('post', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_posts', to='blog.post')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
    ]
